""""Init module"""

import logging
from threading import Lock
from group52.db_accessor.db_connector import DBConnection, Databases
from group52.db_accessor import group52


_LOGGER = None

_DBLOCK = None
_STATION_ACC = None
_REPORT_ACC = None
_EXTREME_ACC = None


def get_logger() -> logging.Logger:
    global _LOGGER

    if not _LOGGER:
        fh = logging.FileHandler("group52.log")
        fh.setFormatter(
            logging.Formatter(
                "[group52] %(asctime)s %(levelname)s %(message)s"
            )  # Formatting options generated by GITHUB COPILOT
        )
        fh.setLevel(logging.DEBUG)

        ch = logging.StreamHandler()
        ch.setLevel(logging.WARN)

        _LOGGER = logging.getLogger(__name__)
        _LOGGER.setLevel(logging.INFO)

        _LOGGER.addHandler(fh)
        _LOGGER.addHandler(ch)

    return _LOGGER


def get_report_accessor() -> tuple[group52.ReportAccessor, Lock]:
    global _DBLOCK, _REPORT_ACC

    if not _DBLOCK:
        _DBLOCK = Lock()

    with _DBLOCK:
        if not _REPORT_ACC:
            try:
                conn = DBConnection(Databases.PROD)
                _REPORT_ACC = group52.ReportAccessor(conn)
                get_logger().info("Connected to database")
            except Exception as e:
                get_logger().error("Failed to connect to database: %s", str(e))

    return _REPORT_ACC, _DBLOCK


def get_station_accessor() -> tuple[group52.ReportAccessor, Lock]:
    global _DBLOCK, _STATION_ACC

    if not _DBLOCK:
        _DBLOCK = Lock()

    with _DBLOCK:
        if not _STATION_ACC:
            try:
                conn = DBConnection(Databases.PROD)
                _STATION_ACC = group52.ReportAccessor(conn)
                get_logger().info("Connected to database")
            except Exception as e:
                get_logger().error("Failed to connect to database: %s", str(e))

    return _STATION_ACC, _DBLOCK


def get_extreme_accessor() -> tuple[group52.ExtremeWeatherAccessor, Lock]:
    global _DBLOCK, _EXTREME_ACC

    if not _DBLOCK:
        _DBLOCK = Lock()

    with _DBLOCK:
        if not _EXTREME_ACC:
            try:
                conn = DBConnection(Databases.PROD)
                _EXTREME_ACC = group52.ExtremeWeatherAccessor(conn)
                get_logger().info("Connected to database")
            except Exception as e:
                get_logger().error("Failed to connect to database: %s", str(e))

    return _EXTREME_ACC, _DBLOCK
