"""
This module defines functions for creating frontend protocol-compliant JSON responses
for group 52's views.
"""

from datetime import datetime
from json import dumps as json_dumps
from typing import Union

import numpy as np

from group52.db_accessor.group52 import Report, Station, Event
from group52.resolvers import get_logger
from group51.utils import create_voronoi, CANADA_BOUNDS


def _generate_time_ticks(
    time_from: datetime, time_to: datetime, jump_months: int = 1
) -> list[str]:
    """
    Generate time ticks between time_from up to time_to, not necessarily including time_to.
    """
    times = []
    while time_from < time_to:
        times.append(str(time_from))
        time_from = datetime(
            time_from.year + (time_from.month + jump_months) // 13,
            1 + (time_from.month - 1 + jump_months) % 12,
            time_from.day,
            time_from.hour,
            time_from.minute,
            time_from.second,
            time_from.microsecond,
        )

    return list(times)


def make_response__reports_meta(
    stations: list[Station], oldest_report_time: datetime
) -> str:
    """
    Creates the `meta` response for the `reports` endpoint.

    Args:
        reporting_stations: The stations presented to the user.
    Returns:
        The meta response JSON string.
    """
    response = {}

    response["timeData"] = {}
    response["timeData"]["batchLoad"] = False
    response["timeData"]["persistent"] = True
    response["timeData"]["partRefetch"] = True
    response["timeData"]["period"] = {"unit": "day"}

    countries = {}  # Use dict as an ordered set
    for station in stations:
        if station.country:
            countries[station.country] = None

    response["timeData"]["times"] = _generate_time_ticks(
        oldest_report_time, datetime.now()
    )
    response["viewCountries"] = list(countries)

    return json_dumps(response)


def make_response__reports(stations: list[Station]) -> str:
    """
    Creates a data-populated response for the `reports` endpoint.

    Args:
        stations: The stations presented to the user.
    Returns:
        The data response JSON string.
    """
    response = {}

    response["clickable"] = True
    response["clustering"] = True
    response["coords"] = [(station.latitude, station.longitude) for station in stations]

    if len(response["coords"]) != len(stations):
        get_logger().warning(
            "Coordinate and station lists are of different length: \
                        coords=%s, stations=%s",
            response["coords"],
            stations,
        )

    response["labels"] = []
    response["ids"] = []

    for station in stations:
        response["ids"].append(station.id)
        response["labels"].append(station.name)

    response["defaultColour"] = "#ffa500"

    return json_dumps(response)


def make_response__reports_part(station_id: str, report: Union[Report, None]) -> str:
    """
    Creates a part response for the `reports` endpoint.

    Args:
        report: The report to present to the user.
    Returns:
        The part response JSON string.
    """
    MSG_UNAVAILABLE = "Missing from Wikidata"

    if report:
        # Conversions generated by GITHUB COPILOT
        avg_high_temp_str = (
            ("%.1f°C" % report.avg_high_temp)
            if report.avg_high_temp is not None
            else MSG_UNAVAILABLE
        )
        avg_low_temp_str = (
            ("%.1f°C" % report.avg_low_temp)
            if report.avg_low_temp is not None
            else MSG_UNAVAILABLE
        )
        avg_temp_str = (
            ("%.1f°C" % report.avg_temp)
            if report.avg_temp is not None
            else MSG_UNAVAILABLE
        )
        precipitation_total_str = (
            ("%.1fmm" % report.precipation_total)
            if report.precipation_total is not None
            else MSG_UNAVAILABLE
        )
        precipation_total_rain_str = (
            ("%.1fmm" % report.precipation_total_rain)
            if report.precipation_total_rain is not None
            else MSG_UNAVAILABLE
        )
        precipitation_total_snow_str = (
            ("%.1fmm" % report.precipation_total_snow)
            if report.precipation_total_snow is not None
            else MSG_UNAVAILABLE
        )
        wind_speed_max_str = (
            ("%.1fkph" % report.wind_speed_max_gust)
            if report.wind_speed_max_gust is not None
            else MSG_UNAVAILABLE
        )

        table = """
            <html>
                <body>
                    <table>
                    <tr>
                        <td><b>Temperature</b> (average)</td>
                        <td>%s</td>
                    </tr>
                    <tr>
                        <td><b>Temperature Highs</b> (average)</td>
                        <td>%s</td>
                    </tr>
                    <tr>
                        <td><b>Temperature Lows</b> (average)</td>
                        <td>%s</td>
                    </tr>
                    <tr>
                        <td><b>Precipitation</b> (total)</td>
                        <td>%s</td>
                    </tr>
                    <tr>
                        <td>..of which rain</td>
                        <td>%s</td>
                    </tr>
                    <tr>
                        <td>..of which snow</td>
                        <td>%s</td>
                    </tr>
                    <tr>
                        <td><b>Wind Speed</b> (maximum)</td>
                        <td>%s</td>
                    </tr>
                    <tr>
                        <td><b>Date Reported</b></td>
                        <td>%s</td>
                    </tr>
                    <tr>
                        <td><b>Wikidata Station Code</b></td>
                        <td>%s</td>
                    </tr>
                    </table>
                </body>
            </html>
            """ % (
            avg_temp_str,
            avg_high_temp_str,
            avg_low_temp_str,
            precipitation_total_str,
            precipation_total_rain_str,
            precipitation_total_snow_str,
            wind_speed_max_str,
            report.time,
            station_id,
        )
        title = "Most relevant monthly report is for " + report.time.strftime("%B, %Y")
    else:
        table = f"<html><body>{MSG_UNAVAILABLE}</body></html>"
        title = "No Reports"

    response = {
        "widget": {
            "title": title,
            "markup": table,
            "size": 0,
        }
    }
    return json_dumps(response)


def make_response__temperature_meta(oldest_report_time: datetime) -> str:
    """
    Creates the `meta` response for the `temperature` endpoint.

    Args:
        oldest_report_time: The oldest report time.
    Returns:
        The meta response JSON string.
    """
    response = {}

    response["timeData"] = {}
    response["timeData"]["batchLoad"] = False
    response["timeData"]["persistent"] = True
    response["timeData"]["period"] = {"unit": "month"}

    response["timeData"]["times"] = _generate_time_ticks(
        oldest_report_time, datetime.now()
    )

    return json_dumps(response)


def make_response__temperature(
    coords_to_temperature: dict[tuple[float, float], float],
    least_recorded_temperature: float,
    greatest_recorded_temperature: float,
) -> str:
    """
    Creates a data-populated response for the `temperature` endpoint.

    Args:
        coords_to_temperature: The temperature data.
        least_recorded_temperature: The least recorded temperature.
        greatest_recorded_temperature: The greatest recorded temperature.
    Returns:
        The data response JSON string.
    """
    response = {}

    response["ids"] = [str(key) for key in coords_to_temperature.keys()]
    polys, vals = create_voronoi(
        np.array(list(coords_to_temperature.keys())),
        np.array(list(coords_to_temperature.values())),
        CANADA_BOUNDS,
    )
    response["polygons"] = polys
    response["values"] = vals
    response["valuesLegend"] = {
        "valueRange": (least_recorded_temperature, greatest_recorded_temperature),
        "units": "°C",
        "colourRange": [
            "magenta",
            "blue",
            "green",
            "yellow",
            "red",
        ],
    }
    response["heatStyle"] = {
        "edgeOpacity": 0.2,
    }
    return json_dumps(response)


def make_response__precipitation_meta(oldest_report_time: datetime) -> str:
    """
    Creates the `meta` response for the `precipitation` endpoint.

    Args:
        oldest_report_time: The oldest report time.
    Returns:
        The meta response JSON string.
    """
    response = {}

    response["timeData"] = {}
    response["timeData"]["batchLoad"] = False
    response["timeData"]["persistent"] = True
    response["timeData"]["period"] = {"unit": "month"}

    response["timeData"]["times"] = _generate_time_ticks(
        oldest_report_time, datetime.now()
    )

    return json_dumps(response)


def make_response__precipitation(
    coords_to_precipitation: dict[tuple[float, float], float],
    least_recorded_precipitation: float,
    greatest_recorded_precipitation: float,
) -> str:
    """
    Creates a data-populated response for the `precipitation` endpoint.

    Args:
        coords_to_precipitation: The precipitation data.
        least_recorded_precipitation: The least recorded precipitation.
        greatest_recorded_precipitation: The greatest recorded precipitation.
    Returns:
        The data response JSON string.
    """
    response = {}

    response["ids"] = [str(key) for key in coords_to_precipitation.keys()]
    polys, vals = create_voronoi(
        np.array(list(coords_to_precipitation.keys())),
        np.array(list(coords_to_precipitation.values())),
        CANADA_BOUNDS,
    )
    response["polygons"] = polys
    response["values"] = vals
    response["valuesLegend"] = {
        "valueRange": (least_recorded_precipitation, greatest_recorded_precipitation),
        "units": "mm",
        "colourRange": ["gray", "blue"],
    }
    response["heatStyle"] = {
        "edgeOpacity": 0.2,
    }
    return json_dumps(response)


def make_response__extreme_events_meta(event_times: list[datetime]) -> str:
    """
    Creates the `meta` response for the `extreme-events` endpoint.

    Args:
        oldest_event_time: The oldest extreme weather event's time.
    Returns:
        The meta response JSON string.
    """
    response = {}

    response["timeData"] = {}
    response["timeData"]["batchLoad"] = False
    response["timeData"]["persistent"] = False
    response["timeData"]["period"] = {"unit": "year"}
    response["timeData"]["times"] = [str(event_time) for event_time in event_times]

    return json_dumps(response)


def make_response__extreme_events(extreme_events: list[Event]) -> str:
    """
    Creates a data-populated response for the `extreme-events` endpoint.

    Args:
        extreme_events: The extreme events.
    Returns:
        The data response JSON string.
    """
    response = {}

    response["clickable"] = False
    response["clustering"] = False
    response["coords"] = [(event.longitude, event.latitude) for event in extreme_events]

    if len(response["coords"]) != len(extreme_events):
        get_logger().warning(
            "Coordinate and extreme events lists are of different length: \
                        coords=%s, stations=%s",
            response["coords"],
            extreme_events,
        )

    response["ids"] = []
    response["labels"] = []

    for event in extreme_events:
        response["ids"].append(event.event_id)
        response["labels"].append(event.event_name)

    response["defaultColour"] = "#ff0000"

    return json_dumps(response)
